# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
    name-server: 127.0.0.1:9876 # RocketMQ Namesrv
    # Producer 配置项
    producer:
        group: demo-producer-group # 生产者分组
        send-message-timeout: 3000 # 发送消息超时时间
        compress-message-body-threshold: 4096 # 消息压缩阀值
        retry-times-when-send-failed: 2 # 同步发送消息时，失败重试次数
        retry-times-when-send-async-failed: 2 # 异步发送时，失败重试次数
        retry-next-server: false # 发送消息给Broker时，如果发送失败，是否重试另外一台Broker
        access-key: # Access Key
        secret-key: # Secret Key
        enable-msg-trace: true # 是否开启消息轨迹功能
        customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义消息轨迹的Topic
    # Consumer 配置项
    consumer:
        listeners: # 配置某个消息分组，是否监听指定Topic。结构为 Map<消息者分组，<Topic, Boolean>>。默认情况下，不配置表示监听
            test-consumer-group:
                topic1: false # 关闭 test-consumer-group 对 topic1 的监听消费
